<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MicrosoftMcp.Common\MicrosoftMcp.Common.csproj" />
    <PackageReference Include="Microsoft.Graph" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Kiota.Abstractions" />
    <PackageReference Include="ModelContextProtocol" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MicrosoftMcp.Outlook.Tests" />
  </ItemGroup>

</Project>
